### ISSUE TITLE
Can't import webtools or pyuspsvalidator 

### ISSUE THREAD

**Issue by bergen288** [michaelwalkerfl/PyUSPSValidator#1]
After installation of pyuspsvalidator , I can import neither pyuspsvalidator  nor webtools with "ModuleNotFoundError" as below.

~~~
Traceback (most recent call last):
  File "c:\Users\User\Documents\VSCode\Python\xxxxxx\test.py", line 9, in <module>
    from webtools import WebToolsRequest
ModuleNotFoundError: No module named 'webtools'
~~~
I checked my site-package, pyuspsvalidator has dist-info subdirectory only.  It doesn't have regular "pyuspsvalidator" subdirectory with Python programs.
What's wrong?
Thanks.

**Comment by michaelwalkerfl** [comment]
Hello, thanks for reporting this issue. Install the latest version from source or pypi `pip install pyuspsvalidator==0.0.4`, then use `from pyuspsvalidator import WebToolsRequest`.
